- name: condiotions
  hosts: localhost
  become: yes
  tasks:
  - name: check roboshop user exist or not
    ansible.builtiin.command: id roboshop
    register: user # user is a variable to store result of above cmd id rosboshop
    ignore_errors: true # ansible will not exist even it got error
  
  - name: print variable value
    ansible.builtin.debug:
      msg: "user output is {{user}}"
  
  - name: print exit status or return code
    ansible.builtin.debug:
      message: "status is {{user.rc}}"
  
  - name: create user
    ansible.builtin.user:
      name: roboshop
    when: user.rc != 0 #condition